# Generated by Django 4.1.7 on 2023-03-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=200)),
                ('neighborhood', models.CharField(max_length=100)),
                ('complement', models.CharField(max_length=50)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=50)),
                ('cat_code', models.IntegerField()),
                ('cat_ctf', models.CharField(max_length=200)),
                ('cod_det', models.IntegerField()),
                ('det_ctf', models.CharField(max_length=200)),
                ('sit_ctf', models.CharField(max_length=200)),
                ('tipo_deb', models.CharField(max_length=200)),
                ('num_deb', models.CharField(max_length=50)),
                ('status_deb', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('porte', models.CharField(max_length=50)),
                ('valor_tcfa', models.CharField(max_length=20)),
                ('ano_deb', models.IntegerField()),
                ('trimestre', models.IntegerField()),
                ('valor_devido_liq', models.CharField(max_length=20)),
            ],
        ),
    ]
