# Generated by Django 4.1.7 on 2023-03-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='ano_deb',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='cat_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='cod_det',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='trimestre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='year',
            field=models.CharField(max_length=200),
        ),
    ]
