# Generated by Django 4.1.7 on 2023-03-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_datatable_ano_deb_alter_datatable_cat_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
