from django.db import models


class DataTable(models.Model):
    id = models.CharField(max_length=10, primary_key=True)
    name = models.CharField(max_length=200)
    cnpj = models.CharField(max_length=11)
    address = models.CharField(max_length=200)
    neighborhood = models.CharField(max_length=100)
    complement = models.CharField(max_length=50)
    number = models.CharField(max_length=50)
    cep = models.CharField(max_length=10)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    uf = models.CharField(max_length=50)
    cat_code = models.CharField(max_length=200)
    cat_ctf = models.CharField(max_length=200)
    cod_det = models.CharField(max_length=200)
    det_ctf = models.CharField(max_length=200)
    sit_ctf = models.CharField(max_length=200)
    tipo_deb = models.CharField(max_length=200)
    num_deb = models.CharField(max_length=50)
    status_deb = models.CharField(max_length=200)
    year = models.CharField(max_length=200)
    porte = models.CharField(max_length=50)
    valor_tcfa = models.CharField(max_length=20)
    ano_deb = models.CharField(max_length=200)
    trimestre = models.CharField(max_length=200)
    valor_devido_liq = models.CharField(max_length=20)
